
var ul=document.createElement("ul");
ul.id="menu";
ul.innerHTML='<li id="nav-1"><a href="javascript:update(1)">View</a></li>\n';
ul.innerHTML+='<li id="nav-2"><a href="javascript:update(2)">Captions</a></li>\n';
ul.innerHTML+='<li id="nav-3"><a href="javascript:update(3)">Versions</a></li>\n';


document.getElementById("watch-player-div").appendChild(ul);
var objDIVContents=document.createElement("div");
objDIVContents.id="cc_DIV_UI_Contents";
objDIVContents.innerHTML='	<div id = "content1" style = "display:none" >\n';

objDIVContents.innerHTML+='<table border = "0" width = "100%" >\n';
objDIVContents.innerHTML+='		<tr>\n';
objDIVContents.innerHTML+='		<td valign = "top">\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='		 <div style = "border: 5px double #ccc; background-color: #E8EBF0; width: 500px ; height: 400px" >\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='		<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="100%" height="100%" id="ccPlayer" align="middle">\n';
objDIVContents.innerHTML+='	  	<param name="allowFullScreen" value="true" />\n';
objDIVContents.innerHTML+=' 	 	<param name="allow-access-from domain" value="*" />\n';
objDIVContents.innerHTML+=' 	 	<param name="allowScriptAccess" value="always" />\n';
objDIVContents.innerHTML+='  		<param name="movie" value="player.swf"/>\n';
objDIVContents.innerHTML+='  		<param name="quality" value="high" />\n';
objDIVContents.innerHTML+='  		<param name="bgcolor" value="#cccccc" />\n';
objDIVContents.innerHTML+='  		<embed src="http://www.projectpossibility.org/projects/webcaption/player.swf" allowfullscreen="true" quality="high" bgcolor="#cccccc"  name="flash" align="middle" id="flash1" allowScriptAccess="always" height="395" width="480" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />\n';
objDIVContents.innerHTML+='  		</object>\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='		 </div>\n';
objDIVContents.innerHTML+='		 \n';
objDIVContents.innerHTML+='		</td>\n';
objDIVContents.innerHTML+='		\n';
objDIVContents.innerHTML+='		<td valign = "top" align = "right" width = "50%">		 		\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			<div align = "left" style = "width : 80% ; font-size: 16px; font-family : courier;" >\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			<br /> \n';
objDIVContents.innerHTML+='			Credits: \n';
objDIVContents.innerHTML+='			<br /><br /> \n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			<ul>\n';
objDIVContents.innerHTML+='			<li> <b> Amgen </b> </li>\n';
objDIVContents.innerHTML+='				<ul>		\n';
objDIVContents.innerHTML+='			    		<li> Ely Lerner </li> \n';
objDIVContents.innerHTML+='				</ul>\n';
objDIVContents.innerHTML+='			</ul>\n';
objDIVContents.innerHTML+='			<ul>\n';
objDIVContents.innerHTML+='			<li> <b> USC </b> </li>\n';
objDIVContents.innerHTML+='				<ul>\n';
objDIVContents.innerHTML+='	    				<li> Jeffrey Chan </li>\n';
objDIVContents.innerHTML+='		    			<li> Chaitanya Ramavajjala </li>\n';
objDIVContents.innerHTML+='		    			<li> Chetan Sharma </li>\n';
objDIVContents.innerHTML+='    					<li> Raed Shomali </li>\n';
objDIVContents.innerHTML+='				</ul> \n';
objDIVContents.innerHTML+='			</ul>\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			</div>\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='		</td>\n';
objDIVContents.innerHTML+='		</tr>\n';
objDIVContents.innerHTML+='		</table>\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='	</div>\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='	<div id = "content2" style = "display:none">\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='		<table border = "0" width = "100%" >\n';
objDIVContents.innerHTML+='		<tr>\n';
objDIVContents.innerHTML+='		<td valign = "top" width = "50%">\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='		<div style = "border: 5px double #ccc; background-color: #E8EBF0; width: 500px ; height: 400px" >\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='		<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="100%" height="100%" id="ccPlayer" align="middle">\n';
objDIVContents.innerHTML+='	  	<param name="allowFullScreen" value="true" />\n';
objDIVContents.innerHTML+=' 	 	<param name="allow-access-from domain" value="*" />\n';
objDIVContents.innerHTML+=' 	 	<param name="allowScriptAccess" value="always" />\n';
objDIVContents.innerHTML+='  		<param name="movie" value="player.swf"/>\n';
objDIVContents.innerHTML+='  		<param name="quality" value="high" />\n';
objDIVContents.innerHTML+='  		<param name="bgcolor" value="#cccccc" />\n';
objDIVContents.innerHTML+='  		<embed src="http://www.projectpossibility.org/projects/webcaption/player.swf" allowfullscreen="true" quality="high" bgcolor="#cccccc"  name="flash" align="middle" id="flash1" allowScriptAccess="always" height="395" width="480" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />\n';
objDIVContents.innerHTML+='  		</object>\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='		</div>\n';
objDIVContents.innerHTML+='		 \n';
objDIVContents.innerHTML+='		</td>\n';
objDIVContents.innerHTML+='		\n';
objDIVContents.innerHTML+='		<td valign = "top"  align = "right">		 \n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			 <form method = "get" action = "">\n';
objDIVContents.innerHTML+='			     \n';
objDIVContents.innerHTML+='					 <a href="javascript:AddNewRow()">Add Caption</a> <br /><br />\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='						<div id="divCaptions" style="height:300px;overflow:auto">\n';
objDIVContents.innerHTML+='						</div>\n';
objDIVContents.innerHTML+='					 \n';
objDIVContents.innerHTML+='					 <br /><br />\n';
objDIVContents.innerHTML+='					 \n';
objDIVContents.innerHTML+='					 <input id = "captionsButton" type = "button" value = "Save Captions" onClick = "saveCaptions()" /><input type = "reset" value = "Clear" />\n';
objDIVContents.innerHTML+='		 	 </form>\n';
objDIVContents.innerHTML+='		</td>\n';
objDIVContents.innerHTML+='		</tr>\n';
objDIVContents.innerHTML+='		</table>\n';
objDIVContents.innerHTML+='	</div>\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='	<div id = "content3" >\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='		<table border = "0" width = "100%" >\n';
objDIVContents.innerHTML+='		<tr>\n';
objDIVContents.innerHTML+='		<td valign = "top">\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='		 <div style = "border: 5px double #ccc; background-color: #E8EBF0; width: 500px ; height: 400px" >\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='		<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="100%" height="100%" id="ccPlayer" align="middle">\n';
objDIVContents.innerHTML+='	  	<param name="allowFullScreen" value="true" />\n';
objDIVContents.innerHTML+=' 	 	<param name="allow-access-from domain" value="*" />\n';
objDIVContents.innerHTML+=' 	 	<param name="allowScriptAccess" value="always" />\n';
objDIVContents.innerHTML+='  		<param name="movie" value="player.swf"/>\n';
objDIVContents.innerHTML+='  		<param name="quality" value="high" />\n';
objDIVContents.innerHTML+='  		<param name="bgcolor" value="#cccccc" />\n';
objDIVContents.innerHTML+='  		<embed src="http://www.projectpossibility.org/projects/webcaption/player.swf" allowfullscreen="true" quality="high" bgcolor="#cccccc"  name="flash" align="middle" id="flash1" allowScriptAccess="always" height="395" width="480" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />\n';
objDIVContents.innerHTML+='  		</object>\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='		 </div>\n';
objDIVContents.innerHTML+='		 \n';
objDIVContents.innerHTML+='		</td>\n';
objDIVContents.innerHTML+='		\n';
objDIVContents.innerHTML+='		<td valign = "top" align = "right" width = "50%">		 		\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			<div align = "left" style = "width : 80% ; font-size: 16px;" ><br /> Available Versions (4): <br /><br /> </div>\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			<table width = "70%" style = "font-family : courier">\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			<tr>\n';
objDIVContents.innerHTML+='				<td> <b>Version 4:</b> March 23rd 08 </td> <td> <img src = "play.jpg" /> <img src = "save.jpg" /> </td>\n';
objDIVContents.innerHTML+='			</tr>	\n';
objDIVContents.innerHTML+='		\n';
objDIVContents.innerHTML+='			<tr>\n';
objDIVContents.innerHTML+='				<td> <b>Version 3:</b> March 20th 08 </td> <td> <img src = "play.jpg" /> <img src = "save.jpg" /> </td>\n';
objDIVContents.innerHTML+='			</tr>	\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			<tr>\n';
objDIVContents.innerHTML+='				<td> <b>Version 2:</b> March 15th 08 </td> <td> <img src = "play.jpg" /> <img src = "save.jpg" /> </td>\n';
objDIVContents.innerHTML+='			</tr>	\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='			<tr>\n';
objDIVContents.innerHTML+='				<td> <b>Version 1:</b> March 02nd 08 </td> <td> <img src = "play.jpg" /> <img src = "save.jpg" /> </td>\n';
objDIVContents.innerHTML+='			</tr>	\n';
objDIVContents.innerHTML+='	\n';
objDIVContents.innerHTML+='			</table>\n';
objDIVContents.innerHTML+='		</td>\n';
objDIVContents.innerHTML+='		</tr>\n';
objDIVContents.innerHTML+='		</table>\n';
objDIVContents.innerHTML+='\n';
objDIVContents.innerHTML+='	</div>\n';

document.getElementById("watch-player-div").appendChild(objDIVContents);

update(1);